layout: default
title: Nick Copelin
email: admin@nickcopelin.com
description: "A professional nameplate site for Nick Copelin"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 08b5da #80B3FF
  secondary: 404040 #FD6E8A
  secondary-dark: 202020 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nickcopelin
  - title: linkedin
    url: http://linkedin.com/in/nickcopelin
  - title: medium
  	url: http://medium.com/@nickcopelin


# Postal address (add as many lines as necessary)


# Build settings
markdown: kramdown
permalink: pretty
encoding: UTF-8
gems:
  - jekyll-sitemap
