layout: default
title: Nick Copelin
email: nick.copelin@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 949494 #80B3FF
  secondary: 08b5da #FD6E8A
  secondary-dark: 666666 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nickcopelin
  - title: linkedin
    url: http://linkedin.com/in/nickcopelin


# Postal address (add as many lines as necessary)


# Build settings
markdown: kramdown
permalink: pretty
encoding: UTF-8
gems:
  - jekyll-sitemap
